// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local mock API instead of remote Supabase due to network connectivity issues
const SUPABASE_URL = "http://localhost:3001";
const SUPABASE_PUBLISHABLE_KEY = "mock-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url, options = {}) => {
      return fetch(url, {
        ...options,
        timeout: 5000, // 5 second timeout for faster fallback
      });
    },
  },
});